/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "By crossbreeding traditional monsters, you can discover exciting NEW creeps and fiends, never before imagined.": "通过杂交传统怪物，您可以发现令人兴奋的新怪物和恶魔，这是前所未有的。",
    "Day Mode": "白天模式",
    "designer monsters": "设计怪物",
    "LOG ▼": "日志 ▼",
    "Music": "音乐",
    "No Music": "静音",
    "People have grown tired of the same old scares. The real money is in": "人们已经厌倦了同样的旧有的恐惧。 真正的钱在",
    "Restart Game": "重新开始",
    "So let's go breed some monsters!": "所以让我们去繁殖一些怪物吧！",
    "STATS ▼": "统计 ▼",
    "Toggle Music": "切换音乐",
    "You are a monster breeder.": "你是一个怪物饲养员。",
    "Browse the catalog": "浏览目录",
    "Created by": "作者是",
    "From here you can visit your monsters in the stables, browse the breeder catalog, or get in your truck and go exploring.": "从这里您可以访问马厩中的怪物，浏览饲养员目录，或坐上卡车去探索。",
    "Game Saved.": "游戏已保存。",
    "Go Exploring": "去探索",
    "Ko-Fi": "高保真",
    "Visit the monster stables": "参观怪物马厩",
    "You are at your ranch.": "你在你的牧场。",
    "CITY": "城市",
    "←Back": "←返回",
    "DESERT": "沙漠",
    "Drive to the city": "开车去市区",
    "Drive to the desert": "开车去沙漠",
    "Drive to the woods": "开车去树林",
    "Exploring local hotspots is a great way to find and capture wild monsters.": "探索当地热点是寻找和捕捉野生怪物的好方法。",
    "RANCH": "牧场",
    "To the east is THE CITY.": "东边是城市。",
    "To the north are THE WOODS.": "北边是树林。",
    "To the south is THE DESERT.": "南边是沙漠。",
    "WOODS": "树林",
    "You load up your gear into your truck.": "您将装备装入卡车。",
    "A few items catch your eye in Monster Breeder Direct": "怪物饲养员指导中的一些项目吸引了您的眼球",
    "Aquatic Monster Specialty Gear": "水生怪物专用装备",
    "Aerial Monster Specialty Gear": "空中怪物专用装备",
    "Better get out there and find some new monsters!": "最好出去寻找一些新的怪物！",
    "←Drive back to the ranch": "←开车回牧场",
    "←Return to your truck": "←返回你的卡车",
    "Drive to the suburbs": "开车去郊区",
    "exp./imp.": "出口/进口",
    "Explore the city": "探索这座城市",
    "MARK MAP": "标记地图",
    "SUBURBS": "郊区",
    "tip": "提示",
    "To the north are THE SUBURBS.": "北边是郊区。",
    "You drive to THE CITY. If you can find parking, there are plenty of monsters to encounter here.": "你开车到城市。 如果你能找到停车位，这里有很多怪物可以遇到。",
    "You park your truck and bring your monster-catching gear out into the city.": "您将卡车停好，然后将捕捉怪物的装备带入城市。",
    "• and SCI-FI ORIGINS": "• 和科幻起源",
    "• BITING ABILITY": "• 咬合能力",
    "• FUTURISTIC LOOK": "• 未来感外观",
    "• HAIRLESSNESS": "• 无毛",
    "• MANUFACTURE": "• 生产",
    "• SWIMMING ABILITY": "• 游泳能力",
    "• WEAPON SKILLS": "• 武器技能",
    "Breeding monsters without official certification by the National Board of Monster Breeders can result in fines of up to $50,000.": "未经国家怪物饲养员委员会的官方认证饲养怪物可能会导致高达 $50,000 的罚款。",
    "Build An Addition To Your Stables": "为您的马厩增建一个新的设施",
    "Comfortably seats up to nine average size monsters or two large monsters. Can also fit one colossal monster.": "最多可舒适地容纳九个中等大小的怪物或两个大型怪物。 也能装下一只巨大的怪物。",
    "Doomsday Monster Rig XXXXL": "世界末日怪物钻机 XXXXL",
    "Holds up to six average size monsters with ease. Can also fit one large monster.": "可轻松容纳多达 6 个中等大小的怪物。 也可以容纳一只大型怪物。",
    "MEDIUM Weight Class": "中等重量级",
    "Meh, who needs a license? What a bunch of bureaucratic nonsense.": "嗯，谁需要许可证？ 真是一堆官僚主义的废话。",
    "Monster Beauty Pageant": "怪物选美大赛",
    "Monster Beauty Pageant Flyer": "怪物选美大赛传单",
    "Monster Breeding License": "怪物饲养许可证",
    "Monster Pheromones": "怪物信息素",
    "Monsters gifted with flight won't evade this high-grade specially-designed monster-catching gear.": "有飞行天赋的怪物不会躲避这种高级的专门设计的怪物捕获装备。",
    "Mosier's humanely extracted monster pheromones are guaranteed to increase your monster encounters. Simply slather your clothes and hair with this patented mix of monster secretions and you'll be spooked from all directions. That's Mosier's guarantee!": "莫谢尔 以人道方式提取的怪物信息素保证会增加您遇到的怪物。 只需将这种获得专利的怪物分泌物混合物涂在你的衣服和头发上，你就会被四面八方的吓到。 这是 莫谢尔 的保证！",
    "Mosier's Monster Phero-\"Moans\"™": "莫谢尔 的怪物 Phero-\"Moans\"™",
    "One monster per breeder allowed per contest. New contests held regularly. Entry fees will not be refunded.": "每场比赛允许每个饲养员一只怪物。 定期举办新的比赛。 报名费将不予退还。",
    "Shriek Shuttle XXL": "尖叫穿梭机 XXL",
    "Stables Addition": "添加马厩",
    "The biggest monster transport on the market! Can easily fit two gigantic monsters, four large monsters, or fifteen average size monsters.": "市场上最大的怪物运输工具！ 可以轻松容纳两个巨型怪物、四个大型怪物或十五个中等大小的怪物。",
    "The Creature Rover XL": "生物漫游者 XL",
    "Water-dwelling monsters are no match for this high-grade specially-designed monster-catching gear.": "专门设计的高级捕兽装备，水栖怪物根本无法匹敌。",
    "We are now accepting entries! Show monsters will be judged based on": "我们现在开始接受报名！ 表演怪物将根据",
    "Your current stables comfortably houses 20 monsters. Building an addition would increase your safe capacity to 35.": "您当前的马厩可轻松容纳 20 只怪物。 建造一个附加物会将您的安全容量增加到 35。",
    "You're walking along the castle moat. The water looks filthy.": "你正沿着城堡护城河走。 水看起来很脏。",
    "You're passing through the castle's stone entranceway.": "你正在穿过城堡的石头入口。",
    "You're on a tremendous wooden drawbridge.": "你在一个巨大的木制吊桥上。",
    "You're on a large spiral staircase.": "你在一个大的螺旋楼梯上。",
    "You're in the northeast spire. There's an ornate coffin here.": "你在东北尖顶。 这里有一个华丽的棺材。",
    "You're in the northwest spire. The bricks here are crumbling.": "你在西北尖顶。 这里的砖块正在崩塌。",
    "You're in a narrow secret passageway.": "你在一条狭窄的秘密通道里。",
    "You're in a library. The books are packed into shelves two stories high. Occasionally, a book seems to move.": "你在图书馆。 这些书被装在两层楼高的书架上。 偶尔，一本书似乎在移动。",
    "You're in a dusty sitting room. The walls are decorated by gray, distorted paintings.": "你在一个尘土飞扬的客厅里。 墙壁上装饰着灰色、扭曲的画作。",
    "You're in a dungeon. Various bones are scattered about the floor.": "你在地牢里。 各种骨头散落在地板上。",
    "You're in a dining room. There's a sprawling, empty dining table, but no chairs.": "你在饭厅。 有一张宽敞的空餐桌，但没有椅子。",
    "You're in a dining room.": "你在饭厅。",
    "The GARGOYLE flies away! You need specialty aerial monster-catching gear.": "石像幽灵飞走了！您需要专门的空中怪物捕捉装备。",
    "the Leprechaun, one two three! ... Steal me gold and I'll murder ye!": "妖精，一二三！ ......偷我金子，我会杀了你！",
    "There's a fireplace here. A candlestick next to it juts out conspicuously.": "这里有一个壁炉。旁边的烛台显眼地突出来。",
    "three! ... Steal me gold and I'll murder ye!": "三！ ......偷我金子，我会杀了你！",
    "To the east are THE WOODS.": "东边是树林。",
    "To the west is a CASTLE.": "西边是一座城堡。",
    "two three! ... Steal me gold and I'll murder ye!": "二三！ ......偷我金子，我会杀了你！",
    "Uh oh! It's a GIANT OCTOPUS!": "哦哦！这是一只巨大的章鱼！",
    "un, one two three! ... Steal me gold and I'll murder ye!": "嗯，一二三！ ......偷我金子，我会杀了你！",
    "Whoa! A GARGOYLE appears!": "哇！石像幽灵出现！",
    "wo three! ... Steal me gold and I'll murder ye!": "我三！ ......偷我金子，我会杀了你！",
    "Wow! It's COUNT DRACULA!": "哇！是德古拉伯爵！",
    "You drive to the edge of the dark woods. There's a narrow path leading in.": "你开车到黑暗森林的边缘。有一条狭窄的小路通向。",
    "You drive toward the ancient stone CASTLE. Its shape seems to blacken as a thunderstorm gathers overhead.": "您驱车前往古老的石头城堡。当雷暴在头顶聚集时，它的形状似乎变黑了。",
    "You easily nab the LEPRECHAUN!": "您可以轻松抓住 妖精！",
    "You exit the castle and return to your truck.": "您离开城堡并返回您的卡车。",
    "You have 2 monsters": "你有2个怪物",
    "You hear jaunty flute music...": "你听到欢快的长笛音乐......",
    "You hear moaning...": "你听到呻吟...",
    "You leave your truck in front and step toward the castle, bringing along your monster-catching gear.": "您将卡车停在前面，带着捕捉怪物的装备走向城堡。",
    "You pull the candlestick. The fireplace swivels open, revealing a secret passageway!": "你拉烛台。壁炉打开，露出一条秘密通道！",
    "You secure the GHOST in the back of your truck.": "您将 幽灵 固定在卡车后部。",
    "You secure the LEPRECHAUN in the back of your truck.": "您将 妖精 固定在卡车后部。",
    "You skillfully nab the GHOST!": "你巧妙地抓住了幽灵！",
    "You unload your truck and place your new LEPRECHAUN and GHOST in the stables.": "您卸下卡车并将新的 妖精 和 幽灵 放在马厩中。",
    "You're in a candlelit hallway lined with stained glass windows.": "你在一个有彩色玻璃窗的烛光走廊里。",
    ", one two three! ... Steal me gold and I'll murder ye!": "， 一二三！ ......偷我金子，我会杀了你！",
    "! ... Steal me gold and I'll murder ye!": "！ ......偷我金子，我会杀了你！",
    ". Steal me gold and I'll murder ye!": ".偷我金子我就杀了你们！",
    ".. Steal me gold and I'll murder ye!": ".. 偷我金子我就杀了你们！",
    "... Steal me gold and I'll murder ye!": "......偷我金子，我会杀了你！",
    "'m the Leprechaun, one two three! ... Steal me gold and I'll murder ye!": "是妖精，一二三！ ......偷我金子，我会杀了你！",
    "• Ghost": "• 幽灵",
    "• Leprechaun": "• 妖精",
    "aun, one two three! ... Steal me gold and I'll murder ye!": "阿姨，一二三！ ......偷我金子，我会杀了你！",
    "Boo!": "嘘！",
    "Capture Count Dracula": "捕获德古拉伯爵",
    "Capture the Gargoyle": "捕捉石像幽灵",
    "Capture the Ghost": "捕捉幽灵",
    "Capture the Giant Octopus": "捕捉巨型章鱼",
    "Capture the Leprechaun": "捕获小妖精",
    "CASTLE": "城堡",
    "chaun, one two three! ... Steal me gold and I'll murder ye!": "chaun，一二三！ ......偷我金子，我会杀了你！",
    "Continue exploring": "继续探索",
    "Drive to the castle": "乘车前往城堡",
    "e Leprechaun, one two three! ... Steal me gold and I'll murder ye!": "e 妖精，一二三！ ......偷我金子，我会杀了你！",
    "e two three! ... Steal me gold and I'll murder ye!": "二三！ ......偷我金子，我会杀了你！",
    "e! ... Steal me gold and I'll murder ye!": "电子！ ......偷我金子，我会杀了你！",
    "echaun, one two three! ... Steal me gold and I'll murder ye!": "echaun，一二三！ ......偷我金子，我会杀了你！",
    "ee! ... Steal me gold and I'll murder ye!": "哎呀！ ......偷我金子，我会杀了你！",
    "eprechaun, one two three! ... Steal me gold and I'll murder ye!": "妖精，一二三！ ......偷我金子，我会杀了你！",
    "Explore the castle": "探索城堡",
    "Explore the woods": "探索树林",
    "GHOST": "幽灵",
    "Gosh! A LEPRECHAUN appears!": "天哪！妖精出现了！",
    "haun, one two three! ... Steal me gold and I'll murder ye!": "haun，一二三！ ......偷我金子，我会杀了你！",
    "he Leprechaun, one two three! ... Steal me gold and I'll murder ye!": "他妖精，一二三！ ......偷我金子，我会杀了你！",
    "hree! ... Steal me gold and I'll murder ye!": "给！ ......偷我金子，我会杀了你！",
    "I'm the Leprechaun, one two three! ... Steal me gold and I'll murder ye!": "我是妖精，一二三！ ......偷我金子，我会杀了你！",
    "LEPRECHAUN": "妖精",
    "Leprechaun, one two three! ... Steal me gold and I'll murder ye!": "妖精，一二三！ ......偷我金子，我会杀了你！",
    "Look out! A GHOST appears!": "当心！幽灵出现了！",
    "m the Leprechaun, one two three! ... Steal me gold and I'll murder ye!": "米妖精，一二三！ ......偷我金子，我会杀了你！",
    "n, one two three! ... Steal me gold and I'll murder ye!": "n，一二三！ ......偷我金子，我会杀了你！",
    "ne two three! ... Steal me gold and I'll murder ye!": "不二三！ ......偷我金子，我会杀了你！",
    "Night Mode": "夜间模式",
    "o three! ... Steal me gold and I'll murder ye!": "哦三个！ ......偷我金子，我会杀了你！",
    "one two three! ... Steal me gold and I'll murder ye!": "一二三！ ......偷我金子，我会杀了你！",
    "Outside, something soars toward the window...": "外面，有什么东西飞向窗户……",
    "prechaun, one two three! ... Steal me gold and I'll murder ye!": "prechaun，一二三！ ......偷我金子，我会杀了你！",
    "Pull the candlestick": "拉烛台",
    "Put the Ghost in your truck": "把幽灵放在你的卡车里",
    "Put the Leprechaun in your truck": "把小妖精放在你的卡车里",
    "rechaun, one two three! ... Steal me gold and I'll murder ye!": "重新开始，一二三！ ......偷我金子，我会杀了你！",
    "ree! ... Steal me gold and I'll murder ye!": "雷！ ......偷我金子，我会杀了你！",
    "Something flutters in and transforms before your eyes!": "有什么东西在你眼前飘来变去！",
    "Something is emerging from the moat...": "有什么东西从护城河里冒出来了……",
    "sort": "种类",
    "Steal me gold and I'll murder ye!": "偷我金子我就杀了你们！",
    "Talk to the Gremlin": "与小精灵交谈",
    "Talk to the Spectrachaun": "与 Spectrachaun 交谈",
    "Talk to the Techie Monster": "与技术怪物交谈",
    "Talk to the Terminator": "与终结者对话",
    "TECHIE MONSTER": "技术怪物",
    "TECHIE MONSTER!": "技术怪物！",
    "Terminating!": "终止！",
    "TERMINATOR": "终结者",
    "The COOKIE MONSTER recently mated. Give some other monsters a turn!": "饼干怪 最近交配。给其他一些怪物一个回合！",
    "The SHARK swims away! You need specialty aquatic monster-catching gear.": "鲨鱼游走了！您需要专业的水生怪物捕捉装备。",
    "The TERMINATOR recently mated. Give some other monsters a turn!": "终结者最近交配了。给其他一些怪物一个回合！",
    "Their child is a beautiful": "他们的孩子很漂亮",
    "There's a very fancy restaurant here.": "这里有一家非常高档的餐厅。",
    "There's an idling police car nearby.": "附近有一辆闲置的警车。",
    "They're done!": "他们完成了！",
    "This COOKIE MONSTER is an intensely creepy, dimwitted monster!": "这个 饼干怪 是一个非常令人毛骨悚然、愚蠢的怪物！",
    "This COOKIE MONSTER is quite the frightening, hirsute monster!": "这个 饼干怪 是一个非常可怕的长毛怪物！",
    "This COOKIE MONSTER is such a terrifying, unintelligent monster!": "这个饼干怪是一个可怕的，没有智能的怪物！",
    "This GHOST is a particularly fearsome, translucent monster!": "这个幽灵是一个特别可怕的半透明怪物！",
    "This GHOST is a truly bone-chilling, no-legged monster!": "这个 幽灵 是一个真正令人毛骨悚然的无腿怪物！",
    "This GHOST is a very creepy, sad monster!": "这个 幽灵 是一个非常令人毛骨悚然、悲伤的怪物！",
    "This GREMLIN is a particularly terrifying, on the small side monster!": "这小精灵是一个特别可怕的小怪物！",
    "This GREMLIN is quite the fearsome, cute monster!": "这个小精灵是相当可怕、可爱的怪物！",
    "This SPECTRACHAUN is a bone-chilling, ancient crossbreed of a Ghost and a Leprechaun. Beautiful!": "这个 SPECTRACHAUN 是幽灵和妖精的令人毛骨悚然的古老杂交种。美丽的！",
    "This SPECTRACHAUN is a scary, gothic crossbreed of a Ghost and a Leprechaun. Beautiful!": "这个 SPECTRACHAUN 是幽灵和妖精的可怕哥特式杂交品种。美丽的！",
    "This TECHIE MONSTER is a creepy, manufactured crossbreed of a Cookie Monster and a Terminator. Marvelous!": "这款 科技怪 是由 饼干怪 和终结者混合而成的令人毛骨悚然的杂交品种。奇妙！",
    "This TECHIE MONSTER is a frightening, futuristic crossbreed of a Cookie Monster and a Terminator. Amazing!": "这个 科技怪 是 饼干怪 和终结者的可怕的、未来派的杂交品种。令人震惊！",
    "This TERMINATOR is a truly frightening, futuristic monster!": "这个终结者是一个真正可怕的未来派怪物！",
    "This TERMINATOR is such a spine-tingling, manufactured monster!": "这个终结者是一个令人毛骨悚然的人造怪物！",
    "ting!": "叮！",
    "tweet": "鸣叫",
    "ve Terminating!": "终止！",
    "want cookie!": "想要饼干！",
    "Who should you breed this COOKIE MONSTER with?": "你应该和谁一起培育这个 饼干怪？",
    "Who should you breed this GHOST with?": "你应该和谁一起培育这个 GHOST？",
    "Whoa! A TERMINATOR appears!": "哇！终结者出现！",
    "Wistfully, you set the GREMLIN free into the wilderness.": "你满怀渴望地将小精灵释放到了荒野中。",
    "With a heavy heart, you set the SPECTRACHAUN free into the wilderness.": "怀着沉重的心情，您将 SPECTRACHAUN 释放到荒野中。",
    "With a tear in your eye, you set the TERMINATOR free into the wilderness.": "眼中含着泪水，您将 终结者 释放到了荒野中。",
    "yeh nyeh!": "耶耶！",
    "yeh!": "耶！",
    "yehh!": "耶！",
    "Yes": "是的",
    "You are able to capture the GREMLIN!": "你能够捕捉到小幽灵！",
    "You hear a subway train rumbling underground.": "你听到地铁列车在地下隆隆作响。",
    "You hear sirens in the distance.": "你听到远处的警报声。",
    "You manage to bag the COOKIE MONSTER!": "您设法将 饼干怪 装入袋中！",
    "You manage to snap up the TERMINATOR!": "你设法抢购了终结者！",
    "You pass some shady looking teens.": "你通过了一些阴暗的青少年。",
    "You secure the COOKIE MONSTER in the back of your truck.": "您将 饼干怪 固定在卡车后部。",
    "You secure the GREMLIN in the back of your truck.": "您将 小精灵 固定在卡车后部。",
    "You secure the TERMINATOR in the back of your truck.": "您将 终结者 固定在卡车后部。",
    "You unload your truck and place your new TERMINATOR and COOKIE MONSTER in the stables.": "您卸下卡车并将新的 终结者 和 饼干怪 放在马厩中。",
    "You're at the corner of Cello and Crier.": "你在 大提琴 和 呐喊者 的拐角处。",
    "You're at the corner of Crier and Heyday. There's a pier to the south.": "您正处于 呐喊者 和 鼎盛时期 的拐角处。南边有个码头。",
    "You're at the corner of Torpor and Cello.": "你在 麻木 和 大提琴 的拐角处。",
    "You're at the corner of Torpor and Heyday.": "您正处于 麻木 和 鼎盛时期 的拐角处。",
    "You're at the foot of a large, art deco skyscraper.": "您正站在一座装饰艺术风格的大型摩天大楼的脚下。",
    "You're at the intersection of Button and Heyday.": "您正处于 按钮 和全盛时期的交汇处。",
    "You're at the intersection of Button and Mint.": "您正处于 按钮 和 薄荷 的交汇处。",
    "You're at the intersection of Cello and Button.": "你在大提琴和巴顿的交汇处。",
    "You're at the intersection of Cello and Vision.": "您正处于大提琴和视觉的交汇处。",
    "You're at the intersection of Cello and Window.": "你在大提琴和窗口的交汇处。",
    "You're at the intersection of Heyday and Step.": "您正处于 鼎盛时期 和 Step 的交汇处。",
    "You're at the intersection of Mint and Beauty.": "您正处于薄荷与美容的交汇处。",
    "You're at the intersection of Mint and Crier.": "您正处于 薄荷 和 呐喊者 的交汇处。",
    "You're at the intersection of Torpor and Mint.": "您正处于 麻木 和 薄荷 的交汇处。",
    "You're in a cold alley.": "你在一个冷巷。",
    "You're in a filthy alley.": "你在一条肮脏的小巷里。",
    "You're in a normal alley.": "你在一条普通的小巷里。",
    "You're on a pier. It smells like fish.": "你在码头上。它闻起来像鱼。",
    "You're on Beauty Street.": "你在美容街。",
    "You're on Button Street.": "你在按钮街。",
    "You're on Cello Street.": "你在大提琴街。",
    "You're on Crier Drive.": "你在 哭泣大道。",
    "You're on Heyday Street.": "你在鼎盛街。",
    "You're on Mint Avenue.": "你在薄荷大道。",
    "You're on Step Street.": "你在步街。",
    "You're on Torpor Street.": "你在 麻木 街。",
    "You've successfully bred the COOKIE MONSTER and the TERMINATOR together.": "你已经成功地培育出了 饼干怪 和 终结者。",
    "You've successfully bred the GHOST and the LEPRECHAUN together.": "你已经成功地培育出了 幽灵 和 妖精。",
    "Your truck doesn't have enough room for an EVIL CAR!": "您的卡车没有足够的空间容纳 邪恶的汽车！",
    "I'm a computer!": "我是电脑！",
    "inating!": "开始！",
    "It looks like the COOKIE MONSTER and the TERMINATOR are mating!": "看起来 饼干怪 和 终结者 正在交配！",
    "It looks like the GHOST and the LEPRECHAUN are mating!": "看起来 幽灵 和 妖精 正在交配！",
    "kie!": "凯！",
    "Leprechaun": "妖精",
    "love Terminating!": "爱终结！",
    "m a computer!": "我是电脑！",
    "M HASTA! MEAN? IT'S, NOM, HASTA, COOKIE NOMM!": "哈斯塔！意思？它是，NOM，HASTA，COOKIE NOMM！",
    "Me want cookie!": "我要饼干！",
    "MEAN? IT'S, NOM, HASTA, COOKIE NOMM!": "意思？它是，NOM，HASTA，COOKIE NOMM！",
    "minating!": "结束！",
    "MURDER. BOO? YE. MEAN BOO WORSE THESE!": "谋杀。嘘？耶。更糟糕的是这些！",
    "nating!": "纳闷！",
    "NO": "不",
    "NOM HASTA!": "哈斯塔！",
    "NOM HASTA! MEAN? IT'S, NOM, HASTA, COOKIE NOMM!": "哈斯塔！意思？它是，NOM，HASTA，COOKIE NOMM！",
    "nt cookie!": "不是饼干！",
    "nyeh!": "哎呀！",
    "Nyehh": "尼耶",
    "Nyehh!": "哎呀！",
    "O MURDER. BOO? YE. MEAN BOO WORSE THESE!": "哦谋杀。嘘？耶。更糟糕的是这些！",
    "Oh dear! It's an EVIL CAR!": "哦亲爱的！这是一辆邪恶的汽车！",
    "okie!": "好的！",
    "OM HASTA! MEAN? IT'S, NOM, HASTA, COOKIE NOMM!": "哦哈斯塔！意思？它是，NOM，HASTA，COOKIE NOMM！",
    "OO MURDER. BOO? YE. MEAN BOO WORSE THESE!": "哦谋杀。嘘？耶。更糟糕的是这些！",
    "ookie!": "哎呀！",
    "ove Terminating!": "结束！",
    "Put the Cookie Monster in your truck": "把饼干怪兽放在你的卡车里",
    "Put the Gremlin in your truck": "将 小精灵 放入您的卡车",
    "Put the Terminator in your truck": "把终结者放在你的卡车里",
    "Release the Cookie Monster": "释放饼干怪物",
    "Release the Ghost": "释放幽灵",
    "Release the Gremlin": "释放小精灵",
    "Release the Spectrachaun": "释放光谱",
    "Release the Techie Monster": "释放技术怪物",
    "Release the Terminator": "释放终结者",
    "rminating!": "结束！",
    "Some businessmen pass by.": "一些商人路过。",
    "Something claws at your feet...": "有什么东西在你的脚边...",
    "Something emerges from a dark corner...": "有什么东西从黑暗的角落里冒出来……",
    "Something jumps out from the ocean!": "有什么东西从海里跳出来了！",
    "Something knocks against a trash can.": "有什么东西撞到了垃圾桶。",
    "SPECTRACHAUN": "SPECTRACHAUN",
    "SPECTRACHAUN!": "SPECTRACHAUN！",
    "STA! MEAN? IT'S, NOM, HASTA, COOKIE NOMM!": "斯塔！意思？它是，NOM，HASTA，COOKIE NOMM！",
    "t cookie!": "饼干！",
    "TA! MEAN? IT'S, NOM, HASTA, COOKIE NOMM!": "TA！意思？它是，NOM，HASTA，COOKIE NOMM！",
    "Talk to the Cookie Monster": "与饼干怪兽交谈",
    "Talk to the Ghost": "与幽灵交谈",
    "MURDER COOKIE NOMM STEAL? NOM NOM CLOVERS!": "谋杀 COOKIE NOMM 偷窃？ NOM NOM 三叶草！",
    "NOM CLOVERS!": "NOM 三叶草！",
    "NOM NOM CLOVERS!": "NOM NOM 三叶草！",
    "NOMM STEAL? NOM NOM CLOVERS!": "诺姆偷？ NOM NOM 三叶草！",
    "O! MYEP GREM BOOOO BEE. NYEH! MEAN BOOOOOOOOOOOO!": "哦！ MYEP GREM BOOOO 蜜蜂。耶！意思是BOOOOOOOOOOOOO！",
    "O? GREM, BOOO!": "哦？格林，嘘！",
    "O? GREM. BOO? GREM, BOOO!": "哦？格雷姆。嘘？格林，嘘！",
    "OKIE NOMM STEAL? NOM NOM CLOVERS!": "OKIE NOMM 偷窃？ NOM NOM 三叶草！",
    "OM CLOVERS!": "哦，四叶草！",
    "OM NOM CLOVERS!": "OM NOM 三叶草！",
    "OMM STEAL? NOM NOM CLOVERS!": "OMM偷？ NOM NOM 三叶草！",
    "OO! MYEP GREM BOOOO BEE. NYEH! MEAN BOOOOOOOOOOOO!": "哦！ MYEP GREM BOOOO 蜜蜂。耶！意思是BOOOOOOOOOOOOO！",
    "OO? GREM, BOOO!": "哦？格林，嘘！",
    "OO? GREM. BOO? GREM, BOOO!": "哦？格雷姆。嘘？格林，嘘！",
    "OOKIE NOMM STEAL? NOM NOM CLOVERS!": "OOKIE NOMM 偷窃？ NOM NOM 三叶草！",
    "OOO! MYEP GREM BOOOO BEE. NYEH! MEAN BOOOOOOOOOOOO!": "哦！ MYEP GREM BOOOO 蜜蜂。耶！意思是BOOOOOOOOOOOOO！",
    "OVERS!": "结束！",
    "R COOKIE NOMM STEAL? NOM NOM CLOVERS!": "R 饼干 NOMM 窃取？ NOM NOM 三叶草！",
    "RDER COOKIE NOMM STEAL? NOM NOM CLOVERS!": "RDER 饼干 NOMM 窃取？ NOM NOM 三叶草！",
    "Release the Gremghost": "释放幽灵",
    "Release the Leprechaun": "释放妖精",
    "Release the Lucky Charms Monster": "释放幸运符怪物",
    "REM, BOOO!": "雷姆，嘘！",
    "REM. BOO? GREM, BOOO!": "快速眼动。嘘？格林，嘘！",
    "STEAL? NOM NOM CLOVERS!": "偷？ NOM NOM 三叶草！",
    "Talk to the Gremghost": "与 Gremghost 交谈",
    "Talk to the Leprechaun": "与妖精交谈",
    "Talk to the Lucky Charms Monster": "与幸运符怪物交谈",
    "TEAL? NOM NOM CLOVERS!": "青色？ NOM NOM 三叶草！",
    "This GREMGHOST is a bone-chilling, green-skinned crossbreed of a Gremlin and a Ghost. Amazing!": "这只 绿巨人 是 小精灵 和 幽灵 的令人毛骨悚然的绿色皮肤杂交种。令人震惊！",
    "This GREMGHOST is a fearsome, green crossbreed of a Gremlin and a Ghost. Marvelous!": "这个 绿巨人 是一只可怕的绿色小精灵和幽灵的杂交品种。奇妙！",
    "This GREMGHOST is a fearsome, supernatural crossbreed of a Gremlin and a Ghost. Fantastic!": "这个 绿巨人 是 小精灵 和 幽灵 的可怕的超自然杂交品种。极好的！",
    "This GREMLIN is an extremely spooky, toothy monster!": "这个 小精灵 是一个非常阴森的、长着牙齿的怪物！",
    "This GREMLIN is quite the frightening, nocturnal monster!": "这个 小精灵 是非常可怕的夜行动物！",
    "This LEPRECHAUN is a truly spine-tingling, mythological monster!": "这个 妖精 是一个真正令人毛骨悚然的神话怪物！",
    "This LUCKY CHARMS MONSTER is a bone-chilling, cuddly crossbreed of a Leprechaun and a Cookie Monster. Not bad!": "这个幸运符怪物是妖精和饼干怪物的令人毛骨悚然、可爱的杂交品种。不错！",
    "This LUCKY CHARMS MONSTER is a frightening, furry crossbreed of a Leprechaun and a Cookie Monster. Ooh la la!": "这个幸运符怪物是妖精和饼干怪物的可怕的毛茸茸的杂交品种。哦啦啦！",
    "URDER COOKIE NOMM STEAL? NOM NOM CLOVERS!": "URDER COOKIE NOMM 偷窃？ NOM NOM 三叶草！",
    "VERS!": "版本！",
    "Who should you breed this GREMLIN with?": "你应该和谁一起培育这个小精灵？",
    "Who should you breed this LEPRECHAUN with?": "你应该和谁一起培育这只妖精？",
    "You've successfully bred the GREMLIN and the GHOST together.": "你已经成功地培育出了 GREMLIN 和 GHOST。",
    "You've successfully bred the LEPRECHAUN and the COOKIE MONSTER together.": "你已经成功地培育出了小妖精和饼干怪兽。",
    ", BOO? GREM. BOO? GREM, BOOO!": "，嘘？格雷姆。嘘？格林，嘘！",
    ", BOOO!": "，呸！",
    "? GREM, BOOO!": "?格林，嘘！",
    "? GREM. BOO? GREM, BOOO!": "?格雷姆。嘘？格林，嘘！",
    "? NOM NOM CLOVERS!": "? NOM NOM 三叶草！",
    ". BOO? GREM, BOOO!": ".嘘？格林，嘘！",
    "• Cookie Monster": "• 饼干怪兽",
    "• Gremghost": "• Gremghost",
    "• Gremlin": "• 小精灵",
    "• Lucky Charms Monster": "• 幸运符怪物",
    "←Okay": "←好的",
    "✓ Ghost": "✓ 幽灵",
    "A BOOO! MYEP GREM BOOOO BEE. NYEH! MEAN BOOOOOOOOOOOO!": "嘘！ MYEP GREM BOOOO 蜜蜂。耶！意思是BOOOOOOOOOOOOO！",
    "A, BOO? GREM. BOO? GREM, BOOO!": "一，嘘？格雷姆。嘘？格林，嘘！",
    "AL? NOM NOM CLOVERS!": "艾尔？ NOM NOM 三叶草！",
    "BOO? GREM, BOOO!": "嘘？格林，嘘！",
    "BOO? GREM. BOO? GREM, BOOO!": "嘘？格雷姆。嘘？格林，嘘！",
    "BOOO!": "嘘！",
    "BOOO! MYEP GREM BOOOO BEE. NYEH! MEAN BOOOOOOOOOOOO!": "嘘！ MYEP GREM BOOOO 蜜蜂。耶！意思是BOOOOOOOOOOOOO！",
    "Breed the Gremlin": "培育小精灵",
    "Breed the Leprechaun": "培育妖精",
    "CLOVERS!": "三叶草！",
    "Congratulations!": "恭喜！",
    "Cookie Monster": "饼干怪兽",
    "COOKIE NOMM STEAL? NOM NOM CLOVERS!": "COOKIE NOMM 窃取？ NOM NOM 三叶草！",
    "DER COOKIE NOMM STEAL? NOM NOM CLOVERS!": "DER COOKIE NOMM 偷窃？ NOM NOM 三叶草！",
    "E NOMM STEAL? NOM NOM CLOVERS!": "E NOMM 偷窃？ NOM NOM 三叶草！",
    "EAL? NOM NOM CLOVERS!": "欧洲联盟？ NOM NOM 三叶草！",
    "EM, BOOO!": "EM，BOOO！",
    "EM. BOO? GREM, BOOO!": "电磁。嘘？格林，嘘！",
    "ER COOKIE NOMM STEAL? NOM NOM CLOVERS!": "ER 饼干 NOMM 偷窃？ NOM NOM 三叶草！",
    "ERS!": "ERS！",
    "Ghost": "幽灵",
    "Git游戏": "吉特游戏",
    "GREM, BOOO!": "格林，嘘！",
    "GREM. BOO? GREM, BOOO!": "格雷姆。嘘？格林，嘘！",
    "GREMGHOST": "绿巨人",
    "GREMGHOST!": "绿巨人！",
    "Gremlin": "小精灵",
    "HA BOOO! MYEP GREM BOOOO BEE. NYEH! MEAN BOOOOOOOOOOOO!": "哈呸！ MYEP GREM BOOOO 蜜蜂。耶！意思是BOOOOOOOOOOOOO！",
    "HA, BOO? GREM. BOO? GREM, BOOO!": "哈，布？格雷姆。嘘？格林，嘘！",
    "IE NOMM STEAL? NOM NOM CLOVERS!": "IE NOMM 偷窃？ NOM NOM 三叶草！",
    "It looks like the GREMLIN and the GHOST are mating!": "看起来 小精灵 和 幽灵 正在交配！",
    "It looks like the LEPRECHAUN and the COOKIE MONSTER are mating!": "妖精 和 饼干怪 好像要交配了！",
    "KIE NOMM STEAL? NOM NOM CLOVERS!": "凯诺姆偷窃？ NOM NOM 三叶草！",
    "L? NOM NOM CLOVERS!": "升？ NOM NOM 三叶草！",
    "LOVERS!": "恋人！",
    "LUCKY CHARMS MONSTER": "幸运符怪物",
    "LUCKY CHARMS MONSTER!": "幸运符怪物！",
    "M CLOVERS!": "三叶草！",
    "M NOM CLOVERS!": "M NOM 三叶草！",
    "M STEAL? NOM NOM CLOVERS!": "偷窃？ NOM NOM 三叶草！",
    "M, BOOO!": "米，呸！",
    "M. BOO? GREM, BOOO!": "M. BOO？格林，嘘！",
    "MM STEAL? NOM NOM CLOVERS!": "MM偷？ NOM NOM 三叶草！",
    "MURDER COOKIE": "谋杀饼干",
    "teal me gold and I'll murder ye!": "给我金子，我会杀了你！",
    "The GHOST recently mated. Give some other monsters a turn!": "GHOST 最近交配了。给其他一些怪物一个回合！",
    "The LEPRECHAUN recently mated. Give some other monsters a turn!": "妖精 最近交配了。给其他一些怪物一个回合！",
    "This COOKIE MONSTER is an intensely creepy, cuddly monster!": "这个 饼干怪 是一个非常令人毛骨悚然、可爱的怪物！",
    "This COOKIE MONSTER is such a bone-chilling, unintelligent monster!": "这个 饼干怪 是一个令人毛骨悚然，没有智慧的怪物！",
    "This GHOST is an extremely bone-chilling, ancient monster!": "这个幽灵，是一个让人毛骨悚然的远古怪物！",
    "This GHOST is an extremely terrifying, ancient monster!": "这个幽灵是一个极其恐怖的远古怪物！",
    "This GHOST is quite the bone-chilling, translucent monster!": "这个幽灵是一个让人毛骨悚然的半透明怪物！",
    "This GREMGHOST is a bone-chilling, magical crossbreed of a Ghost and a Gremlin. Wowie!": "这个 绿巨人 是幽灵和小精灵的令人毛骨悚然的神奇杂交。哇！",
    "This GREMGHOST is a spine-tingling, green-skinned crossbreed of a Gremlin and a Ghost. Exciting!": "这只 绿巨人 是 Gremlin 和 幽灵 的绿色皮肤杂交种，令人毛骨悚然。令人兴奋！",
    "This GREMGHOST is a spine-tingling, see-through crossbreed of a Ghost and a Gremlin. Fantastic!": "这个 绿巨人 是幽灵和小精灵的刺痛、透明的杂交品种。极好的！",
    "This GREMGHOST is a spooky, shapeshifting crossbreed of a Gremlin and a Ghost. Ooh la la!": "这个 绿巨人 是 小精灵 和 幽灵 的怪异、变形的杂交品种。哦啦啦！",
    "This GREMLIN is a particularly bone-chilling, miniscule monster!": "这个小精灵是一个特别令人毛骨悚然的微型怪物！",
    "This GREMLIN is a very bone-chilling, nightcrawling monster!": "这个小精灵是一个非常令人毛骨悚然的夜行怪物！",
    "This LEPRECHAUN is a super scary, snuggly monster!": "这个 妖精 是一个超级可怕、贴身的怪物！",
    "This LEPRECHAUN is a truly spine-tingling, old monster!": "这个 妖精 是一个真正令人毛骨悚然的老怪物！",
    "This LEPRECHAUN is a very bone-chilling, attired monster!": "这个妖精是一个非常令人毛骨悚然，穿着打扮的怪物！",
    "This LUCKY CHARMS MONSTER is a bone-chilling, unintelligent crossbreed of a Leprechaun and a Cookie Monster. Beautiful!": "这个幸运符怪物是妖精和饼干怪物的令人毛骨悚然的无智能杂交。美丽的！",
    "This LUCKY CHARMS MONSTER is a spine-tingling, bitey crossbreed of a Leprechaun and a Cookie Monster. Terrific!": "这个幸运符怪物是妖精和饼干怪物的刺痛、咬人的杂交品种。了不起！",
    "This LUCKY CHARMS MONSTER is a terrifying, toothy crossbreed of a Leprechaun and a Cookie Monster. Amazing!": "这个幸运符怪物是妖精和饼干怪物的可怕、长牙杂交。令人震惊！",
    "urder ye!": "快点呀！",
    "WAH HA, BOO!": "哇哈哈，嘘！",
    "WORDS YE!": "词是！",
    "ye!": "耶！",
    "YE!": "耶！",
    "YEP BOO! WAH HA, BOO!": "是的，嘘！哇哈哈，嘘！",
    "YEP BOOOO. HA MYEP BOO! WAH HA, BOO!": "是的，呜呜。哈 MYEP 嘘！哇哈哈，嘘！",
    "You've successfully bred the GHOST and the GREMLIN together.": "你已经成功地培育出了 GHOST 和 GREMLIN。",
    "I'm the Leprechaun, one two three! ... Steal me gold and I'll murder ye": "我是妖精，一二三！ ......偷我金子，我会杀了你",
    "ie!": "IE！",
    "IE? WORDS YE!": "IE？词是！",
    "It looks like the GHOST and the GREMLIN are mating!": "看起来 GHOST 和 GREMLIN 正在交配！",
    "KIE? WORDS YE!": "凯？词是！",
    "l me gold and I'll murder ye!": "我是金子，我会杀了你们！",
    "l murder ye!": "我杀了你们！",
    "ld and I'll murder ye!": "ld，我会杀了你！",
    "LD COOKIE? WORDS YE!": "老饼干？词是！",
    "ll murder ye!": "会杀了你们！",
    "M": "米",
    "M GREM! BOOOO! HA MYEP! BOOOO MEAN NYEEEEH! BOOO, GREM!": "格林！呜呜！哈我的！ BOOOO 意思是 NYEEEEH！嘘，格林！",
    "M! BOOOO! HA MYEP! BOOOO MEAN NYEEEEH! BOOO, GREM!": "米！呜呜！哈我的！ BOOOO 意思是 NYEEEEH！嘘，格林！",
    "Me": "我",
    "me gold and I'll murder ye!": "我是金子，我会杀了你们！",
    "Me want cookie": "我要饼干",
    "murder ye!": "谋杀你们！",
    "MYEP BOO! WAH HA, BOO!": "MYEP 嘘！哇哈哈，嘘！",
    "MYEP BOOOO. HA MYEP BOO! WAH HA, BOO!": "MYEP BOOOO。哈 MYEP 嘘！哇哈哈，嘘！",
    "nd I'll murder ye!": "我会杀了你们！",
    "Ny": "纽约州",
    "Nye": "奈",
    "Nyeh": "聂",
    "O! WAH HA, BOO!": "哦！哇哈哈，嘘！",
    "O. HA MYEP BOO! WAH HA, BOO!": "O. HA MYEP BOO！哇哈哈，嘘！",
    "OKIE? WORDS YE!": "好的？词是！",
    "old and I'll murder ye!": "老了，我会杀了你！",
    "OLD COOKIE? WORDS YE!": "老饼干？词是！",
    "! BOOOO! HA MYEP! BOOOO MEAN NYEEEEH! BOOO, GREM!": "！呜呜！哈我的！ BOOOO 意思是 NYEEEEH！嘘，格林！",
    "! WAH HA, BOO!": "！哇哈哈，嘘！",
    "? WORDS YE!": "?词是！",
    ". HA MYEP BOO! WAH HA, BOO!": ".哈 MYEP 嘘！哇哈哈，嘘！",
    "'ll murder ye!": "会杀了你们！",
    "✓ Gremlin": "✓ 小精灵",
    "A MYEP BOO! WAH HA, BOO!": "一个 MYEP BOO！哇哈哈，嘘！",
    "AH HA, BOO!": "啊哈，嘘！",
    "al me gold and I'll murder ye!": "我是金子，我会杀了你们！",
    "and I'll murder ye!": "我会杀了你！",
    "ant cookie!": "蚂蚁饼干！",
    "B": "乙",
    "Bo": "博",
    "Boo": "嘘",
    "BOO! WAH HA, BOO!": "嘘！哇哈哈，嘘！",
    "BOOOO! HA MYEP! BOOOO MEAN NYEEEEH! BOOO, GREM!": "呜呜！哈我的！ BOOOO 意思是 NYEEEEH！嘘，格林！",
    "BOOOO. HA MYEP BOO! WAH HA, BOO!": "呜呜呜。哈 MYEP 嘘！哇哈哈，嘘！",
    "Breed the Ghost": "培育幽灵",
    "COOKIE MONSTER": "饼干怪兽",
    "cookie!": "曲奇饼！",
    "COOKIE? WORDS YE!": "曲奇饼？词是！",
    "d and I'll murder ye!": "d 我会杀了你！",
    "D COOKIE? WORDS YE!": "D饼干？词是！",
    "d I'll murder ye!": "d 我要杀了你！",
    "der ye!": "得你！",
    "DS YE!": "DS 耶！",
    "e gold and I'll murder ye!": "我会杀了你！",
    "e want cookie!": "我要饼干！",
    "E? WORDS YE!": "乙？词是！",
    "eal me gold and I'll murder ye!": "给我金子，我会杀了你！",
    "EM GREM! BOOOO! HA MYEP! BOOOO MEAN NYEEEEH! BOOO, GREM!": "EM GREM！呜呜！哈我的！ BOOOO 意思是 NYEEEEH！嘘，格林！",
    "EM! BOOOO! HA MYEP! BOOOO MEAN NYEEEEH! BOOO, GREM!": "电磁！呜呜！哈我的！ BOOOO 意思是 NYEEEEH！嘘，格林！",
    "EP BOO! WAH HA, BOO!": "EP BOO！哇哈哈，嘘！",
    "EP BOOOO. HA MYEP BOO! WAH HA, BOO!": "EP BOOOO。哈 MYEP 嘘！哇哈哈，嘘！",
    "er ye!": "呃耶！",
    "GO": "走",
    "GOL": "戈尔",
    "GOLD": "金子",
    "gold and I'll murder ye!": "黄金，我会杀了你！",
    "GOLD COOKIE? WORDS YE!": "金曲奇？词是！",
    "GREM GREM! BOOOO! HA MYEP! BOOOO MEAN NYEEEEH! BOOO, GREM!": "GREM GREM！呜呜！哈我的！ BOOOO 意思是 NYEEEEH！嘘，格林！",
    "GREM! BOOOO! HA MYEP! BOOOO MEAN NYEEEEH! BOOO, GREM!": "格林！呜呜！哈我的！ BOOOO 意思是 NYEEEEH！嘘，格林！",
    "GREMLIN": "小精灵",
    "I'll murder ye!": "我要杀了你们！",
    "• ANIMALITY": "• 动物性",
    "• INSECTLIKE LOOK": "• 昆虫般的外观",
    "• LOUDNESS": "• 音量",
    "✓ Leprechaun": "✓ 妖精",
    ". BEE MEAN. YE YE BOO, CURSE BOO!": ". 蜜蜂的意思。 YE YE BOO，CURSE BOO！",
    ", CURSE BOO!": "，诅咒嘘！",
    "BEE MEAN. YE YE BOO, CURSE BOO!": "蜜蜂的意思。 YE YE BOO，CURSE BOO！",
    "CURSE BOO!": "诅咒嘘！",
    "This GHOST is a truly bone-chilling, miniature monster!": "这个 幽灵 是一个真正令人毛骨悚然的微型怪物！",
    "This SPECTRACHAUN is a fearsome, gothic crossbreed of a Ghost and a Leprechaun. Incredible!": "这个 SPECTRACHAUN 是幽灵和妖精的可怕哥特式杂交品种。 极好的！",
    "This SPECTRACHAUN is a terrifying, bitey crossbreed of a Ghost and a Leprechaun. Amazing!": "这个 SPECTRACHAUN 是幽灵和小妖精的可怕杂交品种。 令人震惊！",
    "This COOKIE MONSTER is quite the scary, dimwitted monster!": "这个 饼干怪 是一个非常可怕、愚蠢的怪物！",
    "This GHOST is a very terrifying, magical monster!": "这个幽灵是一个非常可怕的神奇怪物！",
    "This GREMLIN is an extremely scary, bitey monster!": "这个小精灵是一个非常可怕，咬人的怪物！",
    "This LEPRECHAUN is a particularly bone-chilling, old monster!": "这个妖精是一个特别令人毛骨悚然的老怪物！",
    "You secure the CHUPACABRA in the back of your truck.": "您将 CHUPACABRA 固定在卡车后部。",
    "You secure the MUMMY in the back of your truck.": "您将木乃伊固定在卡车后部。",
    "You secure the SKELETON in the back of your truck.": "您将 骷髅 固定在卡车后部。",
    "You squeeze through the crevice into a fiery labyrinth. You hear screams in the distance.": "你挤过裂缝进入一个火热的迷宫。你听到远处的尖叫声。",
    "You step out of your truck into the sprawling desert, monster-catching gear in tow.": "你走出你的卡车进入广阔的沙漠，拖着怪物捕捉装备。",
    "You successfully obtain the SKELETON!": "您成功获得骷髅！",
    "You trek back through the desert to your truck.": "你徒步穿越沙漠回到你的卡车。",
    "You turn on your flashlight and enter the dark cave.": "你打开手电筒，进入黑暗的洞穴。",
    "You unload your truck and place your new MUMMY, CHUPACABRA and SKELETON in the stables.": "您卸下卡车并将新的 木乃伊、CHUPACABRA 和 骷髅 放在马厩中。",
    "You're exploring a deep cave.": "你正在探索一个很深的洞穴。",
    "You're on the east side of the lake.": "你在湖的东边。",
    "You're on the north side of the lake.": "你在湖的北边。",
    "You're on the south side of the lake.": "你在湖的南边。",
    "You're on the west side of the lake.": "你在湖的西边。",
    "You're traveling along the northern wall of the outer layer of the labyrinth.": "你正在沿着迷宫外层的北壁旅行。",
    "You're traveling along the southern wall of the outer layer of the labyrinth.": "你正在沿着迷宫外层的南墙旅行。",
    "You're traveling along the western wall of the outer layer of the labyrinth.": "你正沿着迷宫外层的西墙行进。",
    "You're wandering through the desert.": "你在沙漠中徘徊。",
    "You've successfully bred the CHUPACABRA and the COOKIE MONSTER together.": "您已成功将 CHUPACABRA 和 饼干怪 培育在一起。",
    "You've successfully bred the MUMMY and the SKELETON together.": "你已经成功地培育出了木乃伊和骷髅。",
    "Your truck doesn't have enough room for a CYCLOPS!": "您的卡车没有足够的空间容纳 眼巨人！",
    "Your truck doesn't have enough room for a DINOSAUR!": "您的卡车没有足够的空间容纳恐龙！",
    "Your truck doesn't have enough room for a SASQUATCH!": "您的卡车没有足够的空间容纳 野蛮人！",
    "Your truck doesn't have enough room for a ZOMBIE!": "您的卡车没有足够的空间容纳 僵尸！",
    "Yowza! A ZOMBIE appears!": "尤扎！僵尸出现！",
    "I'm the Leprechaun, one two three! .": "我是妖精，一二三！ .",
    "It looks like the CHUPACABRA and the COOKIE MONSTER are mating!": "看起来 CHUPACABRA 和 饼干怪 正在交配！",
    "It looks like the MUMMY and the SKELETON are mating!": "看起来木乃伊和骷髅正在交配！",
    "k out my ribs!": "挖出我的肋骨！",
    "LAKE": "湖",
    "m bones!": "米骨头！",
    "Mummy": "木乃伊",
    "MUMMY": "木乃伊",
    "my ribs!": "我的肋骨！",
    "n!": "啊！",
    "nes!": "尼斯！",
    "nn!": "嗯！",
    "nnn!": "嗯！",
    "nnnn!": "恩恩！",
    "oaannnn!": "啊！",
    "oats": "燕麦",
    "Oh dear! A DINOSAUR appears!": "哦亲爱的！恐龙出现了！",
    "ones!": "那些！",
    "ooaannnn!": "哎呀！",
    "oooaannnn!": "呜呜呜！",
    "out my ribs!": "出我的肋骨！",
    "Put the Chupacabra in your truck": "把卓柏卡布拉放在你的卡车上",
    "Put the Mummy in your truck": "把木乃伊放在你的卡车里",
    "Put the Skeleton in your truck": "把骷髅放在你的卡车上",
    "QQ群号": "QQ群号",
    "Release the Chupacabra": "释放卓柏卡布拉",
    "Release the Mummy": "释放木乃伊",
    "Release the Skeleton": "释放骨架",
    "ribs!": "肋骨！",
    "roooaannnn!": "呜呜呜！",
    "rroooaannnn!": "呜呜呜！",
    "rrroooaannnn!": "呜呜呜！",
    "s": "秒",
    "s!": "！",
    "SKELEMUMMY!": "骷髅妈咪！",
    "Skeleton": "骨骼",
    "SKELETON": "骨骼",
    "Something emerges from the dust...": "有什么东西从尘土中浮现……",
    "Something is emerging from the water...": "有什么东西从水里冒出来了……",
    "Something lurches out of the darkness...": "有什么东西从黑暗中钻了出来……",
    "t my ribs!": "我的肋骨！",
    "Talk to the Chupacabra": "与卓柏卡布拉交谈",
    "Talk to the Mummy": "与木乃伊交谈",
    "Talk to the Skeleton": "与骷髅交谈",
    "The GILL-MAN swims away! You need specialty aquatic monster-catching gear.": "吉尔曼游走！您需要专业的水生怪物捕捉装备。",
    "The SKELETON recently mated. Give some other monsters a turn!": "骨架最近交配。给其他一些怪物一个回合！",
    "There are some discarded sandals here.": "这里有一些废弃的凉鞋。",
    "There's \"NO SWIMMING\" sign here.": "这里有“禁止游泳”的标志。",
    "There's a cave opening here. You hear strange sounds coming from within.": "这里有个洞口。你会听到来自内部的奇怪声音。",
    "There's a crevice in the wall here just big enough to fit through. A hot, red glow emanates from within.": "这里的墙上有一个裂缝，刚好可以穿过。一股炽热的红光从里面散发出来。",
    "There's a dark blue hue to the water here.": "这里的水有一种深蓝色的色调。",
    "There's a gentle wind coming from the north.": "一阵温和的风从北方吹来。",
    "There's a gentle wind coming from the west.": "从西边吹来一阵柔和的风。",
    "There's a modest wind coming from the south.": "有一股温和的风从南方吹来。",
    "There's a modest wind coming from the west.": "有一股温和的风从西边吹来。",
    "There's a rotting old rowboat here.": "这里有一艘破旧的划艇。",
    "There's a slight wind coming from the east.": "有轻微的风从东方吹来。",
    "There's a slight wind coming from the south.": "有轻微的风从南方吹来。",
    "There's a small inlet here with tiny fish swimming around.": "这里有一个小入口，小鱼在周围游来游去。",
    "There's an old rundown house here. It smells of rotting meat.": "这里有一栋破旧的房子。它闻起来有腐烂的肉味。",
    "This CHUPACABRA is an intensely bone-chilling, toothy monster!": "这个 CHUPACABRA 是一个令人毛骨悚然的牙齿怪物！",
    "This LEPRECHAUN is a truly fearsome, miniature monster!": "这个妖精是一个真正可怕的微型怪物！",
    "This LEPRECHAUN is such a bone-chilling, bitey monster!": "这个妖精真是个让人毛骨悚然、咬人的怪物！",
    "This MUMMY is a particularly fearsome, ancient monster!": "这个木乃伊是一个特别可怕的古老怪物！",
    "This SKELETON is an intensely frightening, undead monster!": "这个骷髅是一个非常可怕的不死怪物！",
    "This SKELETON is an intensely spooky, undead monster!": "这个骷髅是一个非常诡异的不死怪物！",
    "To the east is THE DESERT.": "东边是沙漠。",
    "To the west is THE LAKE.": "西边是湖。",
    "ts": "ts",
    "ut my ribs!": "我的肋骨！",
    "Who should you breed this CHUPACABRA with?": "你应该和谁一起培育这个 CHUPACABRA？",
    "Who should you breed this MUMMY with?": "你应该和谁一起培育这个木乃伊？",
    "x": "X",
    "y ribs!": "你的肋骨！",
    "Yikes! A CYCLOPS appears!": "哎呀！独眼巨人出现！",
    "Yikes! A ZOMBIE appears!": "哎呀！僵尸出现！",
    "You artfully ensnare the CHUPACABRA!": "你巧妙地诱捕了 CHUPACABRA！",
    "You backtrack through the labyrinth and cave, and return to your truck.": "您返回迷宫和洞穴，然后返回您的卡车。",
    "You drive into THE DESERT. It stretches on seemingly forever.": "你开车进入沙漠。它似乎永远延伸。",
    "You drive to the serene, still LAKE.": "你开车到宁静的湖边。",
    "You easily obtain the MUMMY!": "您轻松获得木乃伊！",
    "You hear a bloodcurdling sound...": "你听到令人毛骨悚然的声音......",
    "You leave your truck by the lake and begin circling the shore, carrying along your monster-catching gear.": "您将卡车停在湖边，带着捕捉怪物的装备开始在岸边盘旋。",
    "You return to your truck.": "你回到你的卡车上。",
    "• Chupacabra": "•卓柏卡布拉",
    "• Cookiecabra": "• 曲奇卡布拉",
    "• Mummy": "• 木乃伊",
    "• Skelemummy": "• 骷髅",
    "• Skeleton": "• 骨骼",
    "bones!": "骨头！",
    "Breed the Chupacabra": "培育卓柏卡布拉",
    "Breed the Mummy": "培育木乃伊",
    "Capture the Chupacabra": "捕获卓柏卡布拉",
    "Capture the Cyclops": "捕捉独眼巨人",
    "Capture the Dinosaur": "捕捉恐龙",
    "Capture the Gill-Man": "捕获吉尔曼",
    "Capture the Mummy": "捕捉木乃伊",
    "Capture the Sasquatch": "捕捉野人",
    "Capture the Skeleton": "捕捉骷髅",
    "Capture the Zombie": "捕捉僵尸",
    "Check out my ribs!": "看看我的肋骨！",
    "CHUPACABRA": "朱帕卡布拉",
    "ck out my ribs!": "扒开我的肋骨！",
    "COOKIECABRA!": "饼干手心！",
    "Drive to the lake": "开车去湖边",
    "eck out my ribs!": "看看我的肋骨！",
    "Eek! It's a MUMMY!": "哎呀！这是一个木乃伊！",
    "Eep! It's a SKELETON!": "哎呀！这是一个骷髅！",
    "Egad! It's a GILL-MAN!": "哎呀！这是一个吉尔曼！",
    "Enter the cave": "进入洞穴",
    "Enter the crevice": "进入缝隙",
    "Exit the cave": "退出洞穴",
    "Explore the desert": "探索沙漠",
    "Explore the lake": "探索湖泊",
    "Go back through the crevice": "穿过缝隙回去",
    "Goa": "果阿",
    "Goat": "山羊",
    "Goats": "山羊",
    "Great Scott! A SASQUATCH appears!": "伟大的斯科特！ 野蛮人出现！",
    "heck out my ribs!": "滚出我的肋骨！",
    "Holy smokes! A SKELETON appears!": "圣烟！骷髅出现！",
    "Holy smokes! It's a CHUPACABRA!": "圣烟！这是丘帕卡布拉！",
    "Holy smokes! It's a CYCLOPS!": "圣烟！这是一个独眼巨人！",
    "Holy smokes! It's a ZOMBIE!": "圣烟！这是一个僵尸！",
    "I'm the Leprech": "我是妖精",
    "WILL NOT! HA, NOW SHALL!": "将不会！哈，现在应该！",
    "You've successfully bred the CHUPACABRA and the GHOST together.": "你已经成功地培育出了 CHUPACABRA 和 幽灵。",
    "You've successfully bred the CHUPACABRA and the SKELETON together.": "您已经成功地培育出了 CHUPACABRA 和 骷髅。",
    "You've successfully bred the MUMMY and the COOKIE MONSTER together.": "您已经成功地将 木乃伊 和 饼干怪 培育在一起。",
    "You've successfully bred the MUMMY and the GREMLIN together.": "你已经成功地培育出了木乃伊和小精灵。",
    ", GOATS GOAT? RIBS GREAT!": "，山羊山羊？肋骨很棒！",
    ", NOW SHALL!": "，现在！",
    ", OUT, GOATS GOAT? RIBS GREAT!": "，出，山羊山羊？肋骨很棒！",
    "! HA, NOW SHALL!": "！哈，现在应该！",
    "• Chupacasper": "• 卓柏卡斯帕",
    "• Crumby": "• 易碎的",
    "• Grummy": "• 格鲁米",
    "• Skelecabra": "• 骷髅卡布拉",
    "A, NOW SHALL!": "A，现在应该！",
    "aannnn!": "安安！",
    "ALL!": "全部！",
    "annnn!": "安！",
    "AT, OUT, GOATS GOAT? RIBS GREAT!": "AT，出去，山羊山羊？肋骨很棒！",
    "Chupacabra": "卓柏卡布拉",
    "CHUPACASPER!": "丘帕卡斯帕！",
    "CRUMBY!": "易碎！",
    "EAT, OUT, GOATS GOAT? RIBS GREAT!": "吃，出去，山羊 山羊？肋骨很棒！",
    "GREAT, OUT, GOATS GOAT? RIBS GREAT!": "伟大的，出去，山羊山羊？肋骨很棒！",
    "GRUMMY": "格鲁米",
    "GRUMMY!": "恶心！",
    "HA, NOW SHALL!": "哈，现在应该！",
    "HALL!": "大厅！",
    "ILL NOT! HA, NOW SHALL!": "不会！哈，现在应该！",
    "It looks like the CHUPACABRA and the GHOST are mating!": "看起来 CHUPACABRA 和 GHOST 正在交配！",
    "It looks like the CHUPACABRA and the SKELETON are mating!": "看起来 CHUPACABRA 和 SKELETON 正在交配！",
    "It looks like the MUMMY and the COOKIE MONSTER are mating!": "看起来 MUMMY 和 COOKIE MONSTER 正在交配！",
    "It looks like the MUMMY and the GREMLIN are mating!": "看起来木乃伊和小精灵正在交配！",
    "L NOT! HA, NOW SHALL!": "不！哈，现在应该！",
    "LL NOT! HA, NOW SHALL!": "不会！哈，现在应该！",
    "NOT! HA, NOW SHALL!": "不是！哈，现在应该！",
    "NOW SHALL!": "现在应该！",
    "OT! HA, NOW SHALL!": "哦！哈，现在应该！",
    "OUT, GOATS GOAT? RIBS GREAT!": "出去，山羊山羊？肋骨很棒！",
    "OW SHALL!": "哇！",
    "REAT, OUT, GOATS GOAT? RIBS GREAT!": "REAT, OUT, 山羊 山羊？肋骨很棒！",
    "Release the Chupacasper": "释放 Chupacasper",
    "Release the Grummy": "释放 绿乃伊",
    "Release the Skelecabra": "释放骷髅卡布拉",
    "SHALL!": "将！",
    "SKELECABRA": "骷髅头",
    "SKELECABRA!": "骷髅！",
    "T, GOATS GOAT? RIBS GREAT!": "T，山羊山羊？肋骨很棒！",
    "T, OUT, GOATS GOAT? RIBS GREAT!": "T, 出去, 山羊 山羊？肋骨很棒！",
    "T! HA, NOW SHALL!": "太！哈，现在应该！",
    "Talk to the Chupacasper": "与卓柏卡斯帕交谈",
    "Talk to the Grummy": "与 绿乃伊 交谈",
    "Talk to the Skelecabra": "与骷髅王交谈",
    "The MUMMY recently mated. Give some other monsters a turn!": "木乃伊最近交配了。给其他一些怪物一个回合！",
    "This CHUPACABRA is a super creepy, bitey monster!": "这个 CHUPACABRA 是一个超级令人毛骨悚然、咬人的怪物！",
    "This CHUPACABRA is an intensely scary, little monster!": "这个 CHUPACABRA 是一个非常可怕的小怪物！",
    "This CHUPACASPER is a spooky, historical crossbreed of a Chupacabra and a Ghost. Wow!": "这个 CHUPACASPER 是卓柏卡布拉和幽灵的幽灵般的历史杂交品种。哇！",
    "This GRUMMY is a fearsome, undead crossbreed of a Mummy and a Gremlin. Not bad!": "这个 绿乃伊 是木乃伊和小精灵的可怕的不死杂交品种。不错！",
    "This GRUMMY is a spooky, clothed crossbreed of a Mummy and a Gremlin. Ooh la la!": "这款 绿乃伊 是木乃伊和小精灵的怪异穿衣杂交品种。哦啦啦！",
    "This MUMMY is a truly bone-chilling, occult monster!": "这个木乃伊是一个真正令人毛骨悚然的神秘怪物！",
    "This MUMMY is quite the scary, sluggish monster!": "这个木乃伊是一个非常可怕、行动迟缓的怪物！",
    "This MUMMY is such a fearsome, old monster!": "这个木乃伊真是个可怕的老怪物！",
    "This MUMMY is such a terrifying, cursed monster!": "这个木乃伊真是一个可怕的被诅咒的怪物！",
    "This SKELECABRA is a bone-chilling, cute crossbreed of a Chupacabra and a Skeleton. Incredible!": "这款 骷髅卡布拉 是卓柏卡布拉和骷髅的令人毛骨悚然的可爱杂交品种。极好的！",
    "This SKELECABRA is a spooky, legendary crossbreed of a Chupacabra and a Skeleton. Exciting!": "这款 骷髅卡布拉 是卓柏卡布拉和骷髅的怪异传奇杂交品种。令人兴奋！",
    "UT, GOATS GOAT? RIBS GREAT!": "UT，山羊山羊？肋骨很棒！",
    "W SHALL!": "应该！",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Creature Rover XL": "生物漫游者 XL",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Neil Cicierega': 'Neil Cicierega',
    'Patreon': 'Patreon',
    'Paypal': 'Paypal',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Entry fee: ": "入场费：",
    "List price: ": "价格表：",
    "Project cost: ": "项目成本：",
    "The Doomsday Monster Rig": "世界末日怪物钻机",
    "You have: ": "你有: ",
    "With trade-in: ": "以旧换新：",
    "GRAND PRIZE": "大奖",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^Your truck is (.+) full.$/, '您的卡车已装了 $1。'],
    [/^You have (.+) monsters$/, '你有 $1 怪物'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);