/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "By crossbreeding traditional monsters, you can discover exciting NEW creeps and fiends, never before imagined.": "通过杂交传统怪物，您可以发现令人兴奋的新怪物和恶魔，这是前所未有的。",
    "Day Mode": "白天模式",
    "designer monsters": "设计怪物",
    "LOG ▼": "日志 ▼",
    "Music": "音乐",
    "No Music": "静音",
    "People have grown tired of the same old scares. The real money is in": "人们已经厌倦了同样的旧有的恐惧。 真正的钱在",
    "Restart Game": "重新开始",
    "So let's go breed some monsters!": "所以让我们去繁殖一些怪物吧！",
    "STATS ▼": "统计 ▼",
    "Toggle Music": "切换音乐",
    "You are a monster breeder.": "你是一个怪物饲养员。",
    "Browse the catalog": "浏览目录",
    "Created by": "作者是",
    "From here you can visit your monsters in the stables, browse the breeder catalog, or get in your truck and go exploring.": "从这里您可以访问马厩中的怪物，浏览饲养员目录，或坐上卡车去探索。",
    "Game Saved.": "游戏已保存。",
    "Go Exploring": "去探索",
    "Ko-Fi": "高保真",
    "Visit the monster stables": "参观怪物马厩",
    "You are at your ranch.": "你在你的牧场。",
    "CITY": "城市",
    "←Back": "←返回",
    "DESERT": "沙漠",
    "Drive to the city": "开车去市区",
    "Drive to the desert": "开车去沙漠",
    "Drive to the woods": "开车去树林",
    "Exploring local hotspots is a great way to find and capture wild monsters.": "探索当地热点是寻找和捕捉野生怪物的好方法。",
    "RANCH": "牧场",
    "To the east is THE CITY.": "东边是城市。",
    "To the north are THE WOODS.": "北边是树林。",
    "To the south is THE DESERT.": "南边是沙漠。",
    "WOODS": "树林",
    "You load up your gear into your truck.": "您将装备装入卡车。",
    "A few items catch your eye in Monster Breeder Direct": "怪物饲养员指导中的一些项目吸引了您的眼球",
    "Aquatic Monster Specialty Gear": "水生怪物专用装备",
    "Aerial Monster Specialty Gear": "空中怪物专用装备",
    "Better get out there and find some new monsters!": "最好出去寻找一些新的怪物！",
    "←Drive back to the ranch": "←开车回牧场",
    "←Return to your truck": "←返回你的卡车",
    "Drive to the suburbs": "开车去郊区",
    "exp./imp.": "出口/进口",
    "Explore the city": "探索这座城市",
    "MARK MAP": "标记地图",
    "SUBURBS": "郊区",
    "tip": "提示",
    "To the north are THE SUBURBS.": "北边是郊区。",
    "You drive to THE CITY. If you can find parking, there are plenty of monsters to encounter here.": "你开车到城市。 如果你能找到停车位，这里有很多怪物可以遇到。",
    "You park your truck and bring your monster-catching gear out into the city.": "您将卡车停好，然后将捕捉怪物的装备带入城市。",
    "• and SCI-FI ORIGINS": "• 和科幻起源",
    "• BITING ABILITY": "• 咬合能力",
    "• FUTURISTIC LOOK": "• 未来感外观",
    "• HAIRLESSNESS": "• 无毛",
    "• MANUFACTURE": "• 生产",
    "• SWIMMING ABILITY": "• 游泳能力",
    "• WEAPON SKILLS": "• 武器技能",
    "$15,000 GRAND PRIZE": "$15,000 大奖",
    "Breeding monsters without official certification by the National Board of Monster Breeders can result in fines of up to $50,000.": "未经国家怪物饲养员委员会的官方认证饲养怪物可能会导致高达 $50,000 的罚款。",
    "Build An Addition To Your Stables": "为您的马厩增建一个新的设施",
    "Comfortably seats up to nine average size monsters or two large monsters. Can also fit one colossal monster.": "最多可舒适地容纳九个中等大小的怪物或两个大型怪物。 也能装下一只巨大的怪物。",
    "Doomsday Monster Rig XXXXL": "世界末日怪物钻机 XXXXL",
    "Holds up to six average size monsters with ease. Can also fit one large monster.": "可轻松容纳多达 6 个中等大小的怪物。 也可以容纳一只大型怪物。",
    "MEDIUM Weight Class": "中等重量级",
    "Meh, who needs a license? What a bunch of bureaucratic nonsense.": "嗯，谁需要许可证？ 真是一堆官僚主义的废话。",
    "Monster Beauty Pageant": "怪物选美大赛",
    "Monster Beauty Pageant Flyer": "怪物选美大赛传单",
    "Monster Breeding License": "怪物饲养许可证",
    "Monster Pheromones": "怪物信息素",
    "Monsters gifted with flight won't evade this high-grade specially-designed monster-catching gear.": "有飞行天赋的怪物不会躲避这种高级的专门设计的怪物捕获装备。",
    "Mosier's humanely extracted monster pheromones are guaranteed to increase your monster encounters. Simply slather your clothes and hair with this patented mix of monster secretions and you'll be spooked from all directions. That's Mosier's guarantee!": "莫谢尔 以人道方式提取的怪物信息素保证会增加您遇到的怪物。 只需将这种获得专利的怪物分泌物混合物涂在你的衣服和头发上，你就会被四面八方的吓到。 这是 莫谢尔 的保证！",
    "Mosier's Monster Phero-\"Moans\"™": "莫谢尔 的怪物 Phero-\"Moans\"™",
    "One monster per breeder allowed per contest. New contests held regularly. Entry fees will not be refunded.": "每场比赛允许每个饲养员一只怪物。 定期举办新的比赛。 报名费将不予退还。",
    "Shriek Shuttle XXL": "尖叫穿梭机 XXL",
    "Stables Addition": "添加马厩",
    "The biggest monster transport on the market! Can easily fit two gigantic monsters, four large monsters, or fifteen average size monsters.": "市场上最大的怪物运输工具！ 可以轻松容纳两个巨型怪物、四个大型怪物或十五个中等大小的怪物。",
    "The Creature Rover XL": "生物漫游者 XL",
    "Water-dwelling monsters are no match for this high-grade specially-designed monster-catching gear.": "专门设计的高级捕兽装备，水栖怪物根本无法匹敌。",
    "We are now accepting entries! Show monsters will be judged based on": "我们现在开始接受报名！ 表演怪物将根据",
    "Your current stables comfortably houses 20 monsters. Building an addition would increase your safe capacity to 35.": "您当前的马厩可轻松容纳 20 只怪物。 建造一个附加物会将您的安全容量增加到 35。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Creature Rover XL": "生物漫游者 XL",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Neil Cicierega': 'Neil Cicierega',
    'Patreon': 'Patreon',
    'Paypal': 'Paypal',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Entry fee: ": "入场费：",
    "List price: ": "价格表：",
    "Project cost: ": "项目成本：",
    "The Doomsday Monster Rig": "世界末日怪物钻机",
    "You have: ": "你有: ",
    "With trade-in: ": "以旧换新：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);